<?php
/**
 * Regenerates the tiny forwarder files Ianseo's core expects at the hardcoded
 * path Modules/Authentication/ so the real module code can live permanently
 * in Modules/Custom/Authentication/ instead — the one directory Ianseo's own
 * update process never touches (see Modules/Custom/README.TXT in the Ianseo
 * checkout). Everything under Modules/Authentication/ is disposable and gets
 * rewritten on demand: never edit those files directly, edit the ones here.
 *
 * Called from two places, both cheap (an already-current shim short-circuits
 * on the version marker check):
 *   - menu.php, included automatically by Ianseo on every menu build
 *     (Common/Menu.php's Modules/Custom/*\/menu.php glob) — keeps things
 *     healed during normal browsing, including before USERAUTH is ever
 *     turned on (the "Account" link needs Modules/Authentication/index.php
 *     to exist for initial setup).
 *   - Ianseo's root config.php, right after $CFG->USERAUTH is set — the path
 *     that actually matters: Common/BlockDefines.php hard-requires
 *     Modules/Authentication/BlockFunction.php as soon as USERAUTH is true,
 *     and that happens on every request before menu.php is ever reached, so
 *     without this hook a wiped Modules/Authentication/ (e.g. right after an
 *     Ianseo update) would fatal-error every page load until someone noticed
 *     and restored it by hand.
 *
 * Languages/*.php needs no forwarder: it's only ever reached through
 * AuthFunctions.php's own same-directory-relative glob
 * (dirname(__FILE__) . '/Languages/...'), which — once execution has
 * transferred into the real AuthFunctions.php via its forwarder below —
 * already resolves correctly to Modules/Custom/Authentication/Languages/.
 */

if (!function_exists('competplusAuthEnsureShim')) {
    function competplusAuthEnsureShim($documentPath)
    {
        // Bump this when the forwarder templates below change (e.g. a new
        // real file is added to the module), so existing installs pick up
        // the change on their next request instead of keeping a stale shim
        // forever.
        $shimVersion = '2026-08-25.2';

        $shimDir = rtrim($documentPath, '/\\') . '/Modules/Authentication';
        $marker = $shimDir . '/.shim-version';

        if (is_file($marker) && trim((string) @file_get_contents($marker)) === $shimVersion) {
            return;
        }

        if (!is_dir($shimDir) && !@mkdir($shimDir, 0755, true) && !is_dir($shimDir)) {
            // Filesystem not writable from here — nothing more we can do;
            // same failure mode as a manually-deleted module before this
            // bootstrap existed.
            return;
        }

        $header = "<?php\n"
            . "// Auto-generated by Modules/Custom/Authentication/Bootstrap.php.\n"
            . "// Do not edit — this file is rewritten on demand. Edit the real\n"
            . "// file in Modules/Custom/Authentication/ instead.\n";

        // Reachable directly by URL with nothing else loaded yet, so their
        // shim must bootstrap config.php itself before it can use $CFG.
        $entryPoint = function ($real) use ($header) {
            return $header
                . "require_once dirname(__FILE__) . '/../../config.php';\n"
                . "require_once \$CFG->DOCUMENT_PATH . 'Modules/Custom/Authentication/{$real}';\n";
        };
        // Only ever require_once'd from PHP that already bootstrapped
        // config.php ($CFG is already available).
        $includeOnly = function ($real) use ($header) {
            return $header
                . "require_once \$CFG->DOCUMENT_PATH . 'Modules/Custom/Authentication/{$real}';\n";
        };

        $files = array(
            'AuthFunctions.php'      => $includeOnly('AuthFunctions.php'),
            'BlockFunction.php'      => $includeOnly('BlockFunction.php'),
            'CompetplusOAuth.php'    => $includeOnly('CompetplusOAuth.php'),
            'index.php'              => $entryPoint('index.php'),
            'LogIn.php'              => $entryPoint('LogIn.php'),
            'LogOut.php'             => $entryPoint('LogOut.php'),
            'Account.php'            => $entryPoint('Account.php'),
            'CompetplusStart.php'    => $entryPoint('CompetplusStart.php'),
            'CompetplusCallback.php' => $entryPoint('CompetplusCallback.php'),
        );

        $allWritten = true;
        foreach ($files as $name => $content) {
            if (@file_put_contents($shimDir . '/' . $name, $content) === false) {
                $allWritten = false;
            }
        }

        if ($allWritten) {
            @file_put_contents($marker, $shimVersion);
        }
    }
}
